-- begin SAMPLE_BOOK
alter table SAMPLE_BOOK add constraint FK_SAMPLE_BOOK_ON_EBOOK foreign key (EBOOK_ID) references SYS_FILE(ID)^
alter table SAMPLE_BOOK add constraint FK_SAMPLE_BOOK_ON_AUTHOR foreign key (AUTHOR_ID) references SAMPLE_AUTHOR(ID)^
create index IDX_SAMPLE_BOOK_ON_EBOOK on SAMPLE_BOOK (EBOOK_ID)^
create index IDX_SAMPLE_BOOK_ON_AUTHOR on SAMPLE_BOOK (AUTHOR_ID)^
-- end SAMPLE_BOOK
-- begin SAMPLE_CONTRACT_ATTACHMENT
alter table SAMPLE_CONTRACT_ATTACHMENT add constraint FK_SAMPLE_CONTRACT_ATTACHMENT_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
alter table SAMPLE_CONTRACT_ATTACHMENT add constraint FK_SAMPLE_CONTRACT_ATTACHMENT_ON_CONTRACT foreign key (CONTRACT_ID) references SAMPLE_CONTRACT(ID)^
create index IDX_SAMPLE_CONTRACT_ATTACHMENT_ON_FILE on SAMPLE_CONTRACT_ATTACHMENT (FILE_ID)^
create index IDX_SAMPLE_CONTRACT_ATTACHMENT_ON_CONTRACT on SAMPLE_CONTRACT_ATTACHMENT (CONTRACT_ID)^
-- end SAMPLE_CONTRACT_ATTACHMENT
